import re
import sys

def decode_unicode_escapes(match):
    s = match.group(1)
    def replace_hex(m):
        return chr(int(m.group(1), 16))
    decoded = re.sub(r'\\([0-9a-fA-F]{4})', replace_hex, s)
    # Escape single quotes inside the decoded string for safety in MySQL
    decoded_escaped = decoded.replace("'", "''")
    return f"'{decoded_escaped}'"

def convert_line(line):
    # 1. Skip H2-specific lines
    if not line.strip():
        return None
    
    upper_line = line.upper().strip()
    if (upper_line.startswith('SET ') or 
        upper_line.startswith('CREATE USER ') or 
        upper_line.startswith('CREATE ALIAS ') or 
        upper_line.startswith('CREATE CACHED LOCAL TEMPORARY TABLE ') or 
        'SYSTEM_LOB_STREAM' in upper_line or
        upper_line.startswith(';') or
        upper_line == '-- H2 2.1.214;'):
        return None

    # 2. Decode Unicode escapes U&'...'
    line = re.sub(r"U&'([^']*)'", decode_unicode_escapes, line)

    # 3. Replace SYSTEM_COMBINE_BLOB and SYSTEM_COMBINE_CLOB with NULL
    line = re.sub(r"SYSTEM_COMBINE_BLOB\(\d+\)", "NULL", line)
    line = re.sub(r"SYSTEM_COMBINE_CLOB\(\d+\)", "NULL", line)

    # 4. Remove PUBLIC schema prefix
    line = re.sub(r'"PUBLIC"\.', '', line, flags=re.IGNORECASE)
    line = re.sub(r'"public"\.', '', line, flags=re.IGNORECASE)

    # 5. Convert CREATE CACHED TABLE to CREATE TABLE
    line = re.sub(r'CREATE CACHED TABLE', 'CREATE TABLE', line, flags=re.IGNORECASE)

    # 6. Convert column datatypes and identity
    # Match GENERATED BY DEFAULT AS IDENTITY(...) and DEFAULT ON NULL
    line = re.sub(r'GENERATED BY DEFAULT AS IDENTITY\([^)]*\)\s*DEFAULT ON NULL', 'AUTO_INCREMENT', line, flags=re.IGNORECASE)
    line = re.sub(r'GENERATED BY DEFAULT AS IDENTITY\([^)]*\)', 'AUTO_INCREMENT', line, flags=re.IGNORECASE)
    line = re.sub(r'GENERATED BY DEFAULT AS IDENTITY', 'AUTO_INCREMENT', line, flags=re.IGNORECASE)
    
    # Types
    line = re.sub(r'CHARACTER VARYING\((\d+)\)', r'VARCHAR(\1)', line, flags=re.IGNORECASE)
    line = re.sub(r'CHARACTER VARYING', 'VARCHAR(255)', line, flags=re.IGNORECASE)
    line = re.sub(r'DOUBLE PRECISION', 'DOUBLE', line, flags=re.IGNORECASE)
    line = re.sub(r'BINARY LARGE OBJECT', 'LONGBLOB', line, flags=re.IGNORECASE)
    
    # In MySQL, it's safer to use DATETIME instead of TIMESTAMP for general columns from H2
    # But let's only convert TIMESTAMP if it's a column definition type, not in values!
    # H2 inserts values as TIMESTAMP '2026-...'. We should convert TIMESTAMP '...' to '...' or leave it.
    # Actually, MySQL accepts DATETIME '2026-...' or just '2026-...'.
    # Let's replace: COLUMN DEFINITION "col" TIMESTAMP -> DATETIME
    # For now, let's replace TIMESTAMP column type:
    # A simple way is to replace " TIMESTAMP," with " DATETIME," and " TIMESTAMP\)" with " DATETIME)" etc.
    line = re.sub(r'\bTIMESTAMP\b(?!\s+\')', 'DATETIME', line, flags=re.IGNORECASE)

    # 7. Convert double quotes to backticks for identifiers
    line = line.replace('"', '`')

    return line

def main():
    input_file = '../data/efacturacao_dump.sql'
    output_file = '../data/efacturacao_mysql.sql'
    
    print("Starting conversion...")
    count_in = 0
    count_out = 0
    
    with open(input_file, 'r', encoding='utf-8') as f_in, open(output_file, 'w', encoding='utf-8') as f_out:
        # Write MySQL session settings
        f_out.write("-- Script de Base de Dados Convertido de H2 para MySQL\n")
        f_out.write("SET FOREIGN_KEY_CHECKS = 0;\n")
        f_out.write("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n")
        f_out.write("SET NAMES utf8mb4;\n\n")
        
        for line in f_in:
            count_in += 1
            converted = convert_line(line)
            if converted:
                f_out.write(converted)
                count_out += 1
                
        f_out.write("\nSET FOREIGN_KEY_CHECKS = 1;\n")
        
    print(f"Conversion complete! Read {count_in} lines, wrote {count_out} lines.")

if __name__ == '__main__':
    main()
