$inputFile = "d:\eclipse_workspace\facturacao_electronica\data\efacturacao_dump.sql"
$outputFile = "d:\eclipse_workspace\facturacao_electronica\data\efacturacao_mysql.sql"

Write-Host "Starting conversion in PowerShell..."

$utf8NoBOM = New-Object System.Text.UTF8Encoding($false)
$writer = New-Object System.IO.StreamWriter($outputFile, $false, $utf8NoBOM)

$writer.WriteLine("-- Script de Base de Dados Convertido de H2 para MySQL")
$writer.WriteLine("SET FOREIGN_KEY_CHECKS = 0;")
$writer.WriteLine("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';")
$writer.WriteLine("SET NAMES utf8mb4;")
$writer.WriteLine("")

$reader = [System.IO.File]::OpenText($inputFile)
$lineCount = 0
while ($null -ne ($line = $reader.ReadLine())) {
    $lineTrim = $line.Trim()
    if ($lineTrim -eq "") { continue }
    
    $upperLine = $lineTrim.ToUpper()
    if ($upperLine.StartsWith("SET ") -or 
        $upperLine.StartsWith("CREATE USER ") -or 
        $upperLine.StartsWith("CREATE ALIAS ") -or 
        $upperLine.StartsWith("CREATE CACHED LOCAL TEMPORARY TABLE ") -or 
        $upperLine.Contains("SYSTEM_LOB_STREAM") -or
        $upperLine.StartsWith(";") -or
        $upperLine -eq "-- H2 2.1.214;") {
        continue
    }
    
    # Replace SYSTEM_COMBINE_BLOB and CLOB with NULL
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, "SYSTEM_COMBINE_BLOB\(\d+\)", "NULL")
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, "SYSTEM_COMBINE_CLOB\(\d+\)", "NULL")
    
    # Remove PUBLIC schema prefix
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, '"PUBLIC"\.', "", [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, '"public"\.', "", [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    
    # Convert CREATE CACHED TABLE to CREATE TABLE
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, "CREATE CACHED TABLE", "CREATE TABLE", [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    
    # Convert column datatypes and identity
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, 'GENERATED BY DEFAULT AS IDENTITY\([^)]*\)\s*DEFAULT ON NULL', 'AUTO_INCREMENT', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, 'GENERATED BY DEFAULT AS IDENTITY\([^)]*\)', 'AUTO_INCREMENT', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, 'GENERATED BY DEFAULT AS IDENTITY', 'AUTO_INCREMENT', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, 'CHARACTER VARYING\((\d+)\)', 'VARCHAR($1)', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, 'CHARACTER VARYING', 'VARCHAR(255)', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, 'DOUBLE PRECISION', 'DOUBLE', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, 'BINARY LARGE OBJECT', 'LONGBLOB', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, '\bTIMESTAMP\b(?!\s+\'')', 'DATETIME', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    
    # Convert H2 literals: TIMESTAMP '...' -> '...' and DATE '...' -> '...'
    # Use backtick to escape $1 in PowerShell double-quoted replacement string
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, "TIMESTAMP\s+'([^']*)'", "'`$1'", [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, "DATE\s+'([^']*)'", "'`$1'", [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    
    # Convert U&'...' unicode literals
    # Find all matches of U&'...'
    $regexU = [regex]"U&'([^']*)'"
    $matches = $regexU.Matches($line)
    foreach ($m in $matches) {
        $val = $m.Groups[1].Value
        $decoded = [System.Text.RegularExpressions.Regex]::Replace($val, '\\([0-9a-fA-F]{4})', {
            param($mHex)
            [char][int]("0x" + $mHex.Groups[1].Value)
        })
        $decoded = $decoded.Replace("'", "''")
        $line = $line.Replace($m.Value, "'$decoded'")
    }
    
    # Remove H2 specific 'NOCHECK' from foreign key constraints
    $line = [System.Text.RegularExpressions.Regex]::Replace($line, '\s+NOCHECK\b', "", [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    
    # Convert double quotes to backticks
    $line = $line.Replace('"', '`')
    
    $writer.WriteLine($line)
    $lineCount++
}

$reader.Close()
$writer.WriteLine("")
$writer.WriteLine("SET FOREIGN_KEY_CHECKS = 1;")
$writer.Close()

Write-Host "Conversion completed successfully! Processed $lineCount lines."
